filetype plugin indent on       " Allow auto-indenting depending on file type
syntax on                       " Syntax highlighting
set backspace=start,indent,eol  " Allow me to backspace from everywhere
set hidden                      " Allow me to switch buffers without saving

set shiftwidth=2                " Width for autoindents
set tabstop=2                   " Number of columns occupied by a tab 
set softtabstop=2               " See multiple spaces as tabstops so <BS> does the right thing
set expandtab                   " Converts tabs to white space
set autoindent                  " Indent a new line the same amount as the line just typed
set smartindent                 " A little more indentation help

filetype plugin on              " Enable plugin files to be loaded
set showmatch                   " Show matching 
set ignorecase                  " Case insensitive 
set mouse=v                     " Middle-click paste with 
set hlsearch                    " Highlight search 
set incsearch                   " Incremental search
set number                      " Add line numbers
set relativenumber              " Display numbers starting from current line
set wildmode=longest,list       " Get bash-like tab completions
set colorcolumn=120             " Set an 80 column border for good coding style
set clipboard=unnamedplus       " Using system clipboard
set cursorline                  " Highlight current cursorline
set ttyfast                     " Speed up scrolling in Vim
set backupdir=~/.cache/vim      " Directory to store backup files 

highlight ColorColumn ctermbg=DarkMagenta " Set ColorColumn's color


let mapleader=" "             " Map leader key to space

nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>
nnoremap <Leader>e :e $MYVIMRC<CR>
imap kj <Esc>
cmap kj <C-c> 

nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

nnoremap J <C-d>
nnoremap K <C-u>

nnoremap <leader>so :so %<CR>

call plug#begin()

Plug 'habamax/vim-asciidoctor'
Plug 'lordm/vim-browser-reload-linux'

call plug#end()
